require("user.base")
require("user.keymaps")
require("user.plugins")
require("user.theme")
require("user.completion")
require("user.treesitter")
require("rainbow")
require("user.lsp")
require("user.nvimtree") -- remove hyphen to avoid issues
require("user.autopairs")
require("user.null-ls")
require("user.lualine")
require("user.indent-blankline")
